//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverybodyCodesSolutions2024 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverybodyCodesSolutions2024.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CABACACAACAABBCCBBAAACBAACBCACBAACAABBBCCCACCCCABBABABBBCAABBBBBAACBAABAACAAACBCAABBABAACBBBBABCBCBACBBABAABBCAAACBABBABBCCAAAABBBABBBABACACCAAACABBCCABAABACBCBBBABBAABBBAACBCBCCBCBCBAABAABBCBBBBAACBBABBAAACABCABBCACCCCBBCBAACBCCCAAAACCBACBAACBBACCBCABAAABCABBCBACACBBBABCABBCCCACBBACBABBAACCABCCCABABCBBBBCBABCACBCCCABCBCCABCABCACCCCAAACCCBBBCABCBACABABBBCBBCABBBCCCBABCABBCBAACABBBBAACBBAACABCACBBCCBCBACCCABCBABCCCBCBACCAABCBABACCACBABCCABABCCCCCCACBAAACACCACCCBBBCABCBCCBCCAAABCAACAAABCACCAAABCBAACBCBBCACBBA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Task1 {
            get {
                return ResourceManager.GetString("Day1-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDBCAxBCADBAxCBBDBBABADxCDBAxxCABBCxCDxBABACxAADBxBAAABBDCBBAABBADAAABDCBDCDADCCDxACBCBCADBxBCDBAxxCCBAxAxCCxACCDBDxADCAxACCBBDDAABCCBBABDDBDBBABDBDBBDDDDxCBBADDABADDDDDxxCAAxCxCCDCCCAAABCxDAACBCDAAxxDDABCCBCADCBDAABAAxDCxCABBxABCxxACxDBxADABADBCACDCBxCDBxABDDCACBDxxACABBACxAADAAACBBCCxBCBCxDCBDBDCAABCBABAAAxBABCCBDDBBDCBBxACBBBCDBDCBBxCDxACCACxDDBCxCxxBDCBBBBBxCABAxDDDACCCAADBDABBCCADxCABDxDBxAxxCDDBCCBDCACCDxABDCBACCBBCDCAACBDBDCAAACCDBBxDCADCBCCDBCBBCCDDDABDBxDCABBCACDCCxABACACDDBACBADCACDBxDxDDBxxACxAxx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Task2 {
            get {
                return ResourceManager.GetString("Day1-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBADBDBBCAAAABCAAxADDCADxCxDxBCBDBxCxBBBDxCxACxxxCCAxACAxxxABDBDDBDAxDDDxDDADDDBADACAADABCDACDBBCxBCCCCCxxBxxxBBADxxDCxxDDDxCxCBCDACCAxxBDBxCxCxABxCBACDDDDACxDxADADDxBCBBCxDBAADxCDCBAxCBDBACDCxDDBBxBxDAADxCCDAAxCDBAxBxACCCBAACDDAxCDBDCxBDCDCxDBADBABACAxxADDxDBACBDAxDDACBxDCCBCBAxDxCxBBCACxDCxxAAABDBDDxxDCCDBxCxDxxDCCDDABBDBDABACBBCACxxCBBxxDBBBAxDxDDBxABBACCBDDxACABCCBxxxDDACCBCACCBDxACDAABCCBxCAxDBACCBACACDCCxxCCBBDxACDBBBBACDACCAxABxBACBxADCDDDAAxDCCBDBADAxxBAxxxAxCADCDCDCxAADCDBxCxBBBxBDCDAxxCCAACDBDxCBC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Task3 {
            get {
                return ResourceManager.GetString("Day1-Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS:LOR,LL,SI,OR,T.,IS,LA
        ///
        ///LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR. EXCEPTEUR SINT OCCAECAT CUPIDATAT NON PROIDENT, SUNT IN CULPA QUI OFFICIA DESERUNT MOLLIT ANIM ID EST LABORUM..
        /// </summary>
        internal static string Day2_Task1 {
            get {
                return ResourceManager.GetString("Day2-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS:WGEODKZZNM,WG,XZHBUNTMOC,OIGB,GUNAJDRHBE,YLO,WOW,DZ,STRD,KD,T,OO,KBU,MQBXBCJUJF,YZI,GG,PT,L,OW,WKD,YO,RSVBOCFAXQ,EEZB,BFAM,EWF,JXD,XHRN,KIF,VKG,AGKQ,OKDPLSROSQ,ZF,D,Z,XEKR,DZGHHIXSAI,YWUW,DG,MDP,VBPA,TS,HGRNXHDLNB,YXCXOBHVQQ,K,WNGE,AHV,WC,KEHYWSISAY
        ///
        ///HCSIIHRWMXVLZFWKKHNOCBXTKUZEHHBSKTKYFRTZNZBVOTFCWQ
        ///WEMAEEXBBIIBRBKPXTOJXVUUYLSMGZ
        ///MRYJOYAMXIVHNXDZONVMULAPEDYPNKSUWTOMSFMUPKOBQBKTEMRXMFYHZVWO
        ///QQATQIRIVUWAFGHQKVAMZBLULJLZJK
        ///FNGSVEPZKRASKNLDQHVRFBGXPRSIQSXFTYWHYPCJXLCWXNDBJSAKSMGYOALO
        ///RJROKRKNLL
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2_Task2 {
            get {
                return ResourceManager.GetString("Day2-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS:LOL,NMQ,TVZXNWFURI,DIOQCPEUHA,NZJV,UFGP,TTPJBDLQYC,JL,MKT,X,S,RUNFSJRIDU,EY,MS,NKXKBTIOQI,A,FCUT,YORYBQHVZT,ZW,SUV,NNW,IIVQ,BZ,VCIXCHBKQQ,OMUFBKLKYP,DCPF,AZEY,SN,SOX,EJPF,KDDZ,K,LTKY,EV,T,IV,C,PXRMGUPTWS,EVD,G,DFW,SJLCSJHPBC,MFMETEVJWA,OXY,IJD,I,Y,GF,IFRN,UPF,GZ,DP,OMUDLGNFLS,H,SEEIUVMQLD,LO,OAK,IAC,XBA,VHYW,ZZWD,AF,BJU,PGSK,RFC,QOYDIUHJDY,JU,UTNC,KQET,OO,VE,HQVS,CYJYFGZUHY,UYXWPYVOEJ,TW,JXPT,VG,VP,MRO,YAZTVQRPYB,AHC,PZOXWLCVSJ,UWL,FLU,ZYR,JO,LLKD,GP,FNLR,IFAH,MRSLCLUATY,XBJVYPCGMB,CK
        ///
        ///MWYHMRKOTFFRG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2_Task3 {
            get {
                return ResourceManager.GetString("Day2-Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..............................
        ///..............##..............
        ///..........##..##..............
        ///..........#..###.#............
        ///..........#...##.##...........
        ///.........##########...........
        ///.........##############.......
        ///.........############.........
        ///.........###########..........
        ///.............####.##..........
        ///..............#.#.#...........
        ///..................#...........
        ///..................#...........
        ///...............................
        /// </summary>
        internal static string Day3_Task1 {
            get {
                return ResourceManager.GetString("Day3-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......................................................................
        ///......................................................................
        ///......................................................................
        ///...................................#..................................
        ///...............................#..####................................
        ///.........................#..#.##..######..............................
        ///.......................#.##.############..............................
        ///........ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3_Task2 {
            get {
                return ResourceManager.GetString("Day3-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ####################.....................................................#.................................................###################
        ///#.##################...........................................#........##..............................................##.#################.#
        ///###################............................................######....###.#..........................................######################
        ///###################............................................######.#..####### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3_Task3 {
            get {
                return ResourceManager.GetString("Day3-Task3", resourceCulture);
            }
        }
    }
}
