//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverybodyCodesSolutions2024 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverybodyCodesSolutions2024.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CABACACAACAABBCCBBAAACBAACBCACBAACAABBBCCCACCCCABBABABBBCAABBBBBAACBAABAACAAACBCAABBABAACBBBBABCBCBACBBABAABBCAAACBABBABBCCAAAABBBABBBABACACCAAACABBCCABAABACBCBBBABBAABBBAACBCBCCBCBCBAABAABBCBBBBAACBBABBAAACABCABBCACCCCBBCBAACBCCCAAAACCBACBAACBBACCBCABAAABCABBCBACACBBBABCABBCCCACBBACBABBAACCABCCCABABCBBBBCBABCACBCCCABCBCCABCABCACCCCAAACCCBBBCABCBACABABBBCBBCABBBCCCBABCABBCBAACABBBBAACBBAACABCACBBCCBCBACCCABCBABCCCBCBACCAABCBABACCACBABCCABABCCCCCCACBAAACACCACCCBBBCABCBCCBCCAAABCAACAAABCACCAAABCBAACBCBBCACBBA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Task1 {
            get {
                return ResourceManager.GetString("Day1-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDBCAxBCADBAxCBBDBBABADxCDBAxxCABBCxCDxBABACxAADBxBAAABBDCBBAABBADAAABDCBDCDADCCDxACBCBCADBxBCDBAxxCCBAxAxCCxACCDBDxADCAxACCBBDDAABCCBBABDDBDBBABDBDBBDDDDxCBBADDABADDDDDxxCAAxCxCCDCCCAAABCxDAACBCDAAxxDDABCCBCADCBDAABAAxDCxCABBxABCxxACxDBxADABADBCACDCBxCDBxABDDCACBDxxACABBACxAADAAACBBCCxBCBCxDCBDBDCAABCBABAAAxBABCCBDDBBDCBBxACBBBCDBDCBBxCDxACCACxDDBCxCxxBDCBBBBBxCABAxDDDACCCAADBDABBCCADxCABDxDBxAxxCDDBCCBDCACCDxABDCBACCBBCDCAACBDBDCAAACCDBBxDCADCBCCDBCBBCCDDDABDBxDCABBCACDCCxABACACDDBACBADCACDBxDxDDBxxACxAxx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Task2 {
            get {
                return ResourceManager.GetString("Day1-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBADBDBBCAAAABCAAxADDCADxCxDxBCBDBxCxBBBDxCxACxxxCCAxACAxxxABDBDDBDAxDDDxDDADDDBADACAADABCDACDBBCxBCCCCCxxBxxxBBADxxDCxxDDDxCxCBCDACCAxxBDBxCxCxABxCBACDDDDACxDxADADDxBCBBCxDBAADxCDCBAxCBDBACDCxDDBBxBxDAADxCCDAAxCDBAxBxACCCBAACDDAxCDBDCxBDCDCxDBADBABACAxxADDxDBACBDAxDDACBxDCCBCBAxDxCxBBCACxDCxxAAABDBDDxxDCCDBxCxDxxDCCDDABBDBDABACBBCACxxCBBxxDBBBAxDxDDBxABBACCBDDxACABCCBxxxDDACCBCACCBDxACDAABCCBxCAxDBACCBACACDCCxxCCBBDxACDBBBBACDACCAxABxBACBxADCDDDAAxDCCBDBADAxxBAxxxAxCADCDCDCxAADCDBxCxBBBxBDCDAxxCCAACDBDxCBC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Task3 {
            get {
                return ResourceManager.GetString("Day1-Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS:LOR,LL,SI,OR,T.,IS,LA
        ///
        ///LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT, SED DO EIUSMOD TEMPOR INCIDIDUNT UT LABORE ET DOLORE MAGNA ALIQUA. UT ENIM AD MINIM VENIAM, QUIS NOSTRUD EXERCITATION ULLAMCO LABORIS NISI UT ALIQUIP EX EA COMMODO CONSEQUAT. DUIS AUTE IRURE DOLOR IN REPREHENDERIT IN VOLUPTATE VELIT ESSE CILLUM DOLORE EU FUGIAT NULLA PARIATUR. EXCEPTEUR SINT OCCAECAT CUPIDATAT NON PROIDENT, SUNT IN CULPA QUI OFFICIA DESERUNT MOLLIT ANIM ID EST LABORUM..
        /// </summary>
        internal static string Day2_Task1 {
            get {
                return ResourceManager.GetString("Day2-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS:WGEODKZZNM,WG,XZHBUNTMOC,OIGB,GUNAJDRHBE,YLO,WOW,DZ,STRD,KD,T,OO,KBU,MQBXBCJUJF,YZI,GG,PT,L,OW,WKD,YO,RSVBOCFAXQ,EEZB,BFAM,EWF,JXD,XHRN,KIF,VKG,AGKQ,OKDPLSROSQ,ZF,D,Z,XEKR,DZGHHIXSAI,YWUW,DG,MDP,VBPA,TS,HGRNXHDLNB,YXCXOBHVQQ,K,WNGE,AHV,WC,KEHYWSISAY
        ///
        ///HCSIIHRWMXVLZFWKKHNOCBXTKUZEHHBSKTKYFRTZNZBVOTFCWQ
        ///WEMAEEXBBIIBRBKPXTOJXVUUYLSMGZ
        ///MRYJOYAMXIVHNXDZONVMULAPEDYPNKSUWTOMSFMUPKOBQBKTEMRXMFYHZVWO
        ///QQATQIRIVUWAFGHQKVAMZBLULJLZJK
        ///FNGSVEPZKRASKNLDQHVRFBGXPRSIQSXFTYWHYPCJXLCWXNDBJSAKSMGYOALO
        ///RJROKRKNLL
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2_Task2 {
            get {
                return ResourceManager.GetString("Day2-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDS:LOL,NMQ,TVZXNWFURI,DIOQCPEUHA,NZJV,UFGP,TTPJBDLQYC,JL,MKT,X,S,RUNFSJRIDU,EY,MS,NKXKBTIOQI,A,FCUT,YORYBQHVZT,ZW,SUV,NNW,IIVQ,BZ,VCIXCHBKQQ,OMUFBKLKYP,DCPF,AZEY,SN,SOX,EJPF,KDDZ,K,LTKY,EV,T,IV,C,PXRMGUPTWS,EVD,G,DFW,SJLCSJHPBC,MFMETEVJWA,OXY,IJD,I,Y,GF,IFRN,UPF,GZ,DP,OMUDLGNFLS,H,SEEIUVMQLD,LO,OAK,IAC,XBA,VHYW,ZZWD,AF,BJU,PGSK,RFC,QOYDIUHJDY,JU,UTNC,KQET,OO,VE,HQVS,CYJYFGZUHY,UYXWPYVOEJ,TW,JXPT,VG,VP,MRO,YAZTVQRPYB,AHC,PZOXWLCVSJ,UWL,FLU,ZYR,JO,LLKD,GP,FNLR,IFAH,MRSLCLUATY,XBJVYPCGMB,CK
        ///
        ///MWYHMRKOTFFRG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2_Task3 {
            get {
                return ResourceManager.GetString("Day2-Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..............................
        ///..............##..............
        ///..........##..##..............
        ///..........#..###.#............
        ///..........#...##.##...........
        ///.........##########...........
        ///.........##############.......
        ///.........############.........
        ///.........###########..........
        ///.............####.##..........
        ///..............#.#.#...........
        ///..................#...........
        ///..................#...........
        ///...............................
        /// </summary>
        internal static string Day3_Task1 {
            get {
                return ResourceManager.GetString("Day3-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......................................................................
        ///......................................................................
        ///......................................................................
        ///...................................#..................................
        ///...............................#..####................................
        ///.........................#..#.##..######..............................
        ///.......................#.##.############..............................
        ///........ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3_Task2 {
            get {
                return ResourceManager.GetString("Day3-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ####################.....................................................#.................................................###################
        ///#.##################...........................................#........##..............................................##.#################.#
        ///###################............................................######....###.#..........................................######################
        ///###################............................................######.#..####### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3_Task3 {
            get {
                return ResourceManager.GetString("Day3-Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///16
        ///13
        ///18
        ///7
        ///15
        ///13
        ///13
        ///16
        ///17
        ///14.
        /// </summary>
        internal static string Day4_Task1 {
            get {
                return ResourceManager.GetString("Day4-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1077
        ///3933
        ///8330
        ///1461
        ///3940
        ///4057
        ///6952
        ///4210
        ///6678
        ///4232
        ///1834
        ///1487
        ///9361
        ///7631
        ///4588
        ///5318
        ///3646
        ///5146
        ///9116
        ///7406
        ///7915
        ///3890
        ///6697
        ///5802
        ///6592
        ///4183
        ///8205
        ///9128
        ///7191
        ///8244
        ///8554
        ///2888
        ///1209
        ///4051
        ///9189
        ///8848
        ///2838
        ///5561
        ///5578
        ///7999
        ///4930
        ///6966
        ///9052
        ///1775
        ///6476
        ///6431
        ///7277
        ///9874
        ///2197
        ///6694
        ///1001
        ///1852
        ///5218
        ///6019
        ///8095
        ///1180
        ///6898
        ///4697
        ///5879
        ///1213
        ///9330
        ///8534
        ///7212
        ///9091
        ///5044
        ///2962
        ///9824
        ///3003
        ///9484
        ///1031
        ///4975
        ///7900
        ///7455
        ///7970
        ///5127
        ///4467
        ///2785
        ///1598
        ///4337
        ///4676
        ///6313
        ///5540
        ///5952
        ///6059
        ///3704
        ///31 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4_Task2 {
            get {
                return ResourceManager.GetString("Day4-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27665880
        ///27872355
        ///27091688
        ///27482539
        ///27766051
        ///27264889
        ///27403942
        ///27850397
        ///27470919
        ///27935521
        ///27002516
        ///27499631
        ///27259225
        ///27085468
        ///27864693
        ///27077563
        ///27045979
        ///27705306
        ///27934167
        ///27053027
        ///27213220
        ///27294456
        ///27297738
        ///27137438
        ///27670786
        ///27787312
        ///27792440
        ///27395620
        ///27332100
        ///27208918
        ///27021362
        ///27065325
        ///27318757
        ///27878803
        ///27470153
        ///27078788
        ///27854412
        ///27117689
        ///27363260
        ///27385789
        ///27543472
        ///27437570
        ///27109339
        ///27777253
        ///27388245
        ///27891832
        ///27806600
        ///27971853
        ///27886508
        ///27263145
        ///27132221
        ///27 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4_Task3 {
            get {
                return ResourceManager.GetString("Day4-Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 4 4 5
        ///5 4 3 3
        ///5 2 5 2
        ///2 2 4 3
        ///4 3 3 5.
        /// </summary>
        internal static string Day5_Task1 {
            get {
                return ResourceManager.GetString("Day5-Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 61 41 80
        ///95 64 78 87
        ///38 94 62 49
        ///40 45 28 28
        ///39 83 33 68
        ///48 72 35 70
        ///73 55 81 10
        ///13 20 45 89
        ///67 11 30 36
        ///57 17 80 12
        ///53 93 97 81
        ///44 79 20 34
        ///66 55 98 71
        ///37 69 18 14
        ///59 99 17 51
        ///63 16 65 36
        ///42 38 63 98
        ///66 67 94 74
        ///35 90 50 64
        ///29 59 73 19
        ///27 74 83 83
        ///82 45 52 11
        ///56 57 95 68
        ///30 33 28 21
        ///40 85 11 24
        ///25 97 95 37
        ///41 24 19 76
        ///15 22 14 60
        ///64 50 39 86
        ///12 69 38 84
        ///86 75 36 17
        ///27 20 96 45
        ///56 28 61 54
        ///22 33 18 96
        ///81 17 81 79
        ///29 84 43 68
        ///89 34 97 29
        ///26 75 30 59
        ///44 42 52 61
        ///32 85 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5_Task2 {
            get {
                return ResourceManager.GetString("Day5-Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1008 1002 1003 1004
        ///1002 1006 6514 2384
        ///1006 1005 1009 1006
        ///1005 5180 1008 1007
        ///1009 1004 1004 1005
        ///1002 1005 1008 1001
        ///1005 1002 1004 1001
        ///1005 1005 1005 1003
        ///1003 1000 1007 1003
        ///1002 1006 1002 1007
        ///1006 1002 1004 5141
        ///1009 1006 1005 1002
        ///4146 7503 1006 1008
        ///3823 1009 1005 1008
        ///1004 1007 1009 1000
        ///1008 1003 1005 1009
        ///1005 1005 1006 1001
        ///1000 1002 1000 1008
        ///1005 5547 1006 1008
        ///1003 1005 1008 1002
        ///1000 1009 1008 1007
        ///7771 1009 1005 1007
        ///1009 1005 1007 1005
        ///1002 1001 1005 1006
        ///1004 100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5_Task3 {
            get {
                return ResourceManager.GetString("Day5-Task3", resourceCulture);
            }
        }
    }
}
